services:
  backend:
    build: ./annotation-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/app.db
      - SECRET_KEY=your-secret-key
      - SERVER_IP=${SERVER_IP:-localhost}
      - FRONTEND_PORT=${FRONTEND_PORT:-3721}
      - CORS_ORIGINS=["http://localhost:3721","http://127.0.0.1:3721","http://${SERVER_IP:-localhost}:${FRONTEND_PORT:-3721}"]
    volumes:
      - ./annotation-backend:/app
      - ./data:/app/data

  frontend:
    build: ./annotation_ui
    ports:
      - "3721:3721"
    environment:
      - REACT_APP_API_URL=http://${SERVER_IP:-localhost}:8000
    volumes:
      - ./annotation_ui:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  backend_data: 