version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./data:/app/data
    environment:
      - SQLALCHEMY_DATABASE_URL=sqlite:///app/data/app.db
      - FIRST_ADMIN_EMAIL=admin@example.com
      - FIRST_ADMIN_PASSWORD=admin
      - SECRET_KEY=your-secret-key-here
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
    restart: unless-stopped

volumes:
  sqlite_data:
    name: annotation_sqlite_data 